### PR TITLE
es2015 support

### PR DESCRIPTION
**Pull request by sethcall**
Wanting to use this as a dependency, but it's not es2015 compliant (const, let, parameter defaults, etc).

This PR does that.    

I believe I read that it's standard practice these days to try and be es2015 compliant if building a library, for maximal compliance.   Sounds good?

### CODE REVIEW

**Comment by sethcall** [comment]
Thanks!!

**Comment by caub** [comment]
Hey, yw

I integrated your changes (missing a return, and const -> var)

I also pushed a new cleaner and faster version, ES5 too, I'll update it on npm

**Comment by sethcall** [comment]
Big thanks!  I'm all over it.

**Comment by caub** [comment]
note you're also mixing ES2015 (ES6) and ES5

there's still some ES6 in the code like [this](https://github.com/caub/pg-tsquery/blob/master/index.js#L48) should be `{type: type, input: input, ..`

do you really need ES5 (node < 4)? what was your limitation?

**Comment by sethcall** [comment]
I was trying to Uglify my webpage and the inclusion of this script was
causing it to fail.  Uglify is not ES6 compatible (for sure I know it barfs
on *class*, for instance), but maybe it can handle *some* ES2016.

**Comment by caub** [comment]
I wonder what's your usage of this module on the browser-side?
 I use it only on server, and with node >6

**Comment by sethcall** [comment]
It shouldn't be used on the client-side in any public-facing web app.
(unless you wanted to use it to show someone how to translate a normal
query into a PG-OK query as an interactive demo, I suppose).

I was trying to simply use it in a SPA/client-side app that would somehow
talk (more or less) directly to PG.  It's not 'safe'. Could be intranet
only if it were to ever be a real app

**Comment by caub** [comment]
oh ok, fine, I'll make it uglify compatible, yea I know this problem with es6+uglify

**Comment by sethcall** [comment]
I spent some time trying to figure out how one can transpile just one
library in node_modules (which would be a good 'trick' to have; there are
other libraries like this).

I know there must be a reasonable way; but I couldn't find one.  And this
file is so small I said well fine I'll just try to fork it.

**Comment by caub** [comment]
it's easy to do with webpack:

```
loaders: [{
			test: /\.jsx?$/,
			loader: 'babel-loader',
			exclude: /node_modules\/(?!some-package-to-transpile\/)/
		}, ..
```

**Comment by sethcall** [comment]
Dude that's way easy.   I was looking for something way more complicated.

I'm OK to do that instead.  If you don't want to play this 'make your
package ES2015 ' game.

**Pull request merged**
